WPEFRAMEWORK_LAUNCHER_VERSION = e144d9f8afd4ea158c4686f9f4daf2143339cf53
WPEFRAMEWORK_LAUNCHER_SITE = $(call github,WebPlatformForEmbedded,WPEPluginLauncher,$(WPEFRAMEWORK_LAUNCHER_VERSION))
WPEFRAMEWORK_LAUNCHER_INSTALL_STAGING = YES
WPEFRAMEWORK_LAUNCHER_DEPENDENCIES = wpeframework wpeframework-interfaces

ifeq ($(BR2_CMAKE_HOST_DEPENDENCY),)
WPEFRAMEWORK_LAUNCHER_CONF_OPTS += \
       -DCMAKE_MODULE_PATH=$(HOST_DIR)/share/cmake/Modules
endif

WPEFRAMEWORK_LAUNCHER_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_LAUNCHER_VERSION}

$(eval $(cmake-package))

