WPEFRAMEWORK_LAUNCHER_VERSION = e144d9f8afd4ea158c4686f9f4daf2143339cf53
WPEFRAMEWORK_LAUNCHER_SITE = $(call github,WebPlatformForEmbedded,WPEPluginLauncher,$(WPEFRAMEWORK_LAUNCHER_VERSION))
WPEFRAMEWORK_LAUNCHER_INSTALL_STAGING = YES
WPEFRAMEWORK_LAUNCHER_DEPENDENCIES = wpeframework wpeframework-interfaces

WPEFRAMEWORK_LAUNCHER_CONF_OPTS += -DBUILD_REFERENCE=${WPEFRAMEWORK_LAUNCHER_VERSION}

$(eval $(cmake-package))

