################################################################################
#
# wpeframework-disneyplus
#
################################################################################

WPEFRAMEWORK_DISNEYPLUS_VERSION = c9a81dbfc83efd4e7e70d01fbf11c8ce13be0f97
WPEFRAMEWORK_DISNEYPLUS_SITE_METHOD = git
WPEFRAMEWORK_DISNEYPLUS_SITE = git@github.com:WebPlatformForEmbedded/WPEPluginDisneyPlus.git
WPEFRAMEWORK_DISNEYPLUS_INSTALL_STAGING = YES
WPEFRAMEWORK_DISNEYPLUS_DEPENDENCIES = wpeframework disney

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_AUTOSTART),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_AUTOSTART=true
else
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_AUTOSTART=false
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_DEVICE),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_DEVICE="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_DEVICE))"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VENDOR),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_VENDOR="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VENDOR))"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_REGION),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_REGION="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_REGION))"
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_ADVERTISING_ID),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_ADVERTISING_ID="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_ADVERTISING_ID))"
endif

ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_DISPLAY_MODE_720P),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_DISPLAY_MODE=720p
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_DISPLAY_MODE_1080P),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_DISPLAY_MODE=1080p
else ifeq ($(BR2_PACKAGE_WPEFRAMEWORK_DISNEYPLUS_DISPLAY_MODE_2160P),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_DISPLAY_MODE=2160p
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VIDEO_MEMORY),0)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_VIDEO_MEMORY=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_VIDEO_MEMORY)
endif

ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_STACK_SIZE),0)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_STACK_SIZE=$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_STACK_SIZE)
endif
ifneq ($(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_PERSONA_ID),"")
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_PERSONA_ID="$(call qstrip,$(BR2_PACKAGE_WPEFRAMEWORK_PLUGIN_DISNEYPLUS_PERSONA_ID))"
endif


ifeq ($(BR2_PACKAGE_DISNEY_TOOLING_SHIELD_ASSISTANT),y)
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_SHIELD_ASSISTANT=ON
else
WPEFRAMEWORK_DISNEYPLUS_CONF_OPTS += -DPLUGIN_DISNEYPLUS_SHIELD_ASSISTANT=OFF
endif

$(eval $(cmake-package))
