################################################################################
#
# benchflix
#
################################################################################

BENCHFLIX_VERSION = 0a3c168027006d9613d3dd44fae0e9d385d9299f
BENCHFLIX_SITE = git@github.com:Metrological/benchflix.git
BENCHFLIX_SITE_METHOD = git
BENCHFLIX_LICENSE = PROPRIETARY
BENCHFLIX_INSTALL_STAGING = NO
BENCHFLIX_INSTALL_TARGET = YES
BENCHFLIX_DEPENDENCIES = libpng freetype libcurl jpeg openssl gstreamer1 gst-plugins-good gst-plugins-bad
BENCHFLIX_PRE_PATCH_HOOKS += BENCHFLIX_UNTAR_KTX

define BENCHFLIX_UNTAR_KTX
	tar -C $(@D)/3rdParty -xf $(@D)/3rdParty/KTX.tar.gz
endef

ifeq ($(BR2_PACKAGE_BENCHFLIX_PREBUILT_OPENH264),y)
BENCHFLIX_CONF_OPTS += -DUSE_PREBUILT_OPENH264=ON
BENCHFLIX_DEPENDENCIES += libopenh264 
endif

ifeq ($(BR2_PACKAGE_BENCHFLIX_PREBUILT_FDK_AAC),y)
BENCHFLIX_CONF_OPTS += -DUSE_PREBUILT_FDKAAC=ON
BENCHFLIX_DEPENDENCIES += fdk-aac
endif

ifeq ($(BR2_PACKAGE_BENCHFLIX_SCENER),y)

BENCHFLIX_CONF_OPTS += -DBUILD_SCENER=ON
define BENCHFLIX_INSTALL_SCENER
	$(INSTALL) -m 755 $(@D)/scener $(1)/usr/bin
endef

else
BENCHFLIX_CONF_OPTS += -DBUILD_SCENER=OFF
endif

ifeq ($(BR2_PACKAGE_BENCHFLIX_CONFLIX),y)

BENCHFLIX_CONF_OPTS += -DBUILD_CONFLIX=ON
define BENCHFLIX_INSTALL_CONFLIX
$(INSTALL) -m 755 $(@D)/conflix $(1)/usr/bin
endef

else
BENCHFLIX_CONF_OPTS += -DBUILD_CONFLIX=OFF
endif

ifeq ($(BR2_PACKAGE_BENCHFLIX_LOG_LEVEL_1),y)
BENCHFLIX_CONF_OPTS += -DLOGLEVEL=1
else ifeq ($(BR2_PACKAGE_BENCHFLIX_LOG_LEVEL_2),y)
BENCHFLIX_CONF_OPTS += -DLOGLEVEL=2
else ifeq ($(BR2_PACKAGE_BENCHFLIX_LOG_LEVEL_3),y)
BENCHFLIX_CONF_OPTS += -DLOGLEVEL=3
else ifeq ($(BR2_PACKAGE_BENCHFLIX_LOG_LEVEL_4),y)
BENCHFLIX_CONF_OPTS += -DLOGLEVEL=4
endif

ifeq ($(BR2_PACKAGE_BENCHFLIX_GL_DEBUG),y)
BENCHFLIX_CONF_OPTS += -DBGLDEBUG=ON
endif

ifeq ($(BR2_PACKAGE_BENCHFLIX_DPI_DESKTOP),y)
BENCHFLIX_CONF_OPTS += -DDPI=desktop
else ifeq ($(BR2_PACKAGE_BENCHFLIX_DPI_SAMPLE1),y)
BENCHFLIX_CONF_OPTS += -DDPI=sample1
else ifeq ($(BR2_PACKAGE_BENCHFLIX_DPI_SAMPLE2),y)
BENCHFLIX_CONF_OPTS += -DDPI=sample2
else ifeq ($(BR2_PACKAGE_BENCHFLIX_DPI_GSTREAMER),y)
BENCHFLIX_CONF_OPTS += -DDPI=gstreamer
endif

ifeq ($(BR2_PACKAGE_BENCHFLIX_DPI_GSTREAMER_PLATFORM_BCM),y)
BENCHFLIX_CONF_OPTS += -DGSTREAMER_PLATFORM="brcm"
BENCHFLIX_DEPENDENCIES += gst1-bcm
endif

define BENCHFLIX_INSTALL_TARGET_CMDS
	$(INSTALL) -m 755 $(@D)/benchflix $(TARGET_DIR)/usr/bin
	$(INSTALL) -m 755 $(@D)/liblzham.so $(TARGET_DIR)/usr/lib
	$(call BENCHFLIX_INSTALL_SCENER,         $(TARGET_DIR))
	$(call BENCHFLIX_INSTALL_CONFLIX,         $(TARGET_DIR))
endef

$(eval $(cmake-package))
